### ISSUE TITLE
k2. Setting up our server

### ISSUE THREAD

**Issue by dianalimnos** [MakeSchool-Tutorials/sa-2018-node-reddit#4]
It isn't super clear how we are supposed to update our views/layout.hbs file to use Bootstrap's navbar. Also there are a couple comments you may want to take out. 

<img width="800" alt="screen shot 2018-07-06 at 2 09 06 pm" src="https://user-images.githubusercontent.com/20194565/42400442-6f4af5c8-8126-11e8-9753-eb2db0f4e174.png">

<img width="952" alt="screen shot 2018-07-06 at 2 09 27 pm" src="https://user-images.githubusercontent.com/20194565/42400441-6f2c578a-8126-11e8-9178-e60a8699193a.png">

**Comment by dionlarson** [comment]
Fixed
